create table papertypes ( PaperType VarChar(10))

INSERT INTO PAPERTYPES VALUES ( 'BOND' )
INSERT INTO PAPERTYPES VALUES ( 'CART' )
INSERT INTO PAPERTYPES VALUES ( 'CB' )
INSERT INTO PAPERTYPES VALUES ( 'CO' )
INSERT INTO PAPERTYPES VALUES ( 'CRBNLS' )
INSERT INTO PAPERTYPES VALUES ( 'ELEC' )
