CREATE TABLE RollWidth ( RollWidth VarChar(10))

INSERT INTO RollWidth VALUES ('5 3/4' )
INSERT INTO RollWidth VALUES ('6' )    
INSERT INTO RollWidth VALUES ('6 1/4' )
INSERT INTO RollWidth VALUES ('7' )    
INSERT INTO RollWidth VALUES ('7 3/8' )
INSERT INTO RollWidth VALUES ('7 5/8' )
INSERT INTO RollWidth VALUES ('8' )    
INSERT INTO RollWidth VALUES ('8 1/2' )
INSERT INTO RollWidth VALUES ('8 1/8' )
INSERT INTO RollWidth VALUES ('8 3/4' )
INSERT INTO RollWidth VALUES ('8 7/8' )
INSERT INTO RollWidth VALUES ('9' )    
INSERT INTO RollWidth VALUES ('9 1/2' )
INSERT INTO RollWidth VALUES ('9 1/4' )
INSERT INTO RollWidth VALUES ('9 7/8' ) 
INSERT INTO RollWidth VALUES ('10' )   
INSERT INTO RollWidth VALUES ('11' )   
INSERT INTO RollWidth VALUES ('11 1/2' )    
INSERT INTO RollWidth VALUES ('11 5/8' )    
INSERT INTO RollWidth VALUES ('12' )   
INSERT INTO RollWidth VALUES ('12 1/2' )    
INSERT INTO RollWidth VALUES ('12 1/4' )    
INSERT INTO RollWidth VALUES ('12 3/4' )    
INSERT INTO RollWidth VALUES ('12 5/8' )    
INSERT INTO RollWidth VALUES ('13' )   
INSERT INTO RollWidth VALUES ('13 1/2' ) 
INSERT INTO RollWidth VALUES ('14' )   
INSERT INTO RollWidth VALUES ('14 1/2' )    
INSERT INTO RollWidth VALUES ('14 5/8' )    
INSERT INTO RollWidth VALUES ('14 7/8' )    
INSERT INTO RollWidth VALUES ('15' )   
INSERT INTO RollWidth VALUES ('15 1/2' )    
INSERT INTO RollWidth VALUES ('15 1/4' )    
INSERT INTO RollWidth VALUES ('15 3/4' )    
INSERT INTO RollWidth VALUES ('15 7/8' )    
INSERT INTO RollWidth VALUES ('16' )   
INSERT INTO RollWidth VALUES ('16 1/2' )    
INSERT INTO RollWidth VALUES ('17' )   
INSERT INTO RollWidth VALUES ('17 1/2' )    
INSERT INTO RollWidth VALUES ('17 1/4' )    
INSERT INTO RollWidth VALUES ('18' )   
INSERT INTO RollWidth VALUES ('18 1/2' )    
INSERT INTO RollWidth VALUES ('18 1/4' )    
INSERT INTO RollWidth VALUES ('19' )   
INSERT INTO RollWidth VALUES ('19 1/2' )    
INSERT INTO RollWidth VALUES ('19 3/4' )    
INSERT INTO RollWidth VALUES ('20' )   
INSERT INTO RollWidth VALUES ('20 1/4' )    
INSERT INTO RollWidth VALUES ('21' )   
INSERT INTO RollWidth VALUES ('22' )   
INSERT INTO RollWidth VALUES ('22 1/2' )
INSERT INTO RollWidth VALUES ('23' )   
INSERT INTO RollWidth VALUES ('23 1/4' )    
INSERT INTO RollWidth VALUES ('24 1/2' )    
INSERT INTO RollWidth VALUES ('28 3/4' )    
INSERT INTO RollWidth VALUES ('29' )   
INSERT INTO RollWidth VALUES ('29 3/4' )    
INSERT INTO RollWidth VALUES ('34 1/2' )    