CREATE PROCEDURE PartialNameASC
( @Part VarChar(20) )
AS
BEGIN
SELECT * FROM CRC_CU10
 WHERE CUST_NAME LIKE '%' + @Part + '%' 
  ORDER BY CUST_NAME
END

CREATE PROCEDURE PartialNameDESC
( @Part VarChar(20) )
AS
BEGIN
SELECT * FROM CRC_CU10
 WHERE CUST_NAME LIKE '%' + @Part + '%' 
  ORDER BY CUST_NAME DESC
END